php:
  build: ./docker/php
  links:
    - mariadb:mariadb
    - redis:redis
    - rabbit:rabbit
  volumes:
    - .:/var/www/symfony2biso
nginx:
  build: ./docker/nginx
  ports:
    - 8080:80
  links:
    - php:php
    - redis:redis
  volumes_from:
    - php
mariadb:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    TERM: linux
  volumes:
    - ./docker/volumes/mariadb:/var/lib/mysql
redis:
  image: redis:3.2.10-alpine
  volumes:
    - ./docker/volumes/redis:/data
  ports:
    - 6379:6379
rabbit:
  build: ./docker/rabbitmq
  environment:
      - RABBITMQ_PASS=symfony2biso
  ports:
    - 5672:5672
    - 15672:15672
elk:
  image: sebp/elk:E1L1K4
  ports:
    - 5601:5601
  links:
    - redis:redis
  environment:
    TERM: linux
  volumes:
    - ./docker/volumes/elk/logstash:/etc/logstash/conf.d
mockServer:
  image: php:5.6-cli
  ports:
    - 9090:80
  working_dir: /var/www/symfony2biso
  volumes_from:
    - php
  command: php -S 0.0.0.0:80 src/AppBundle/Tests/MockServer/router.php